SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
WHERE O.ANIMAL_ID NOT IN
      (SELECT I.ANIMAL_ID
       FROM ANIMAL_INS AS I)
ORDER BY O.ANIMAL_ID

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
         LEFT JOIN ANIMAL_INS AS I
                   ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID